version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_DETAILS=mongodb://mongodb:27017?retryWrites=true&w=majority

